version: '2'
services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - redis
    environment:
      CELERY_BROKER_URL: redis://redis
  redis:
    image: redis
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - redis
    command: /bin/sh -c  "pip install --editable . && skeleton_web --listen=:80"
    volumes:
      - .:/code
    environment:
      DEBUG: 1
